services:
  - type: web
    name: jtkidz
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
